collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      permalink: "author/:slug"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "post/:slug"
  - scope:
      path: ""
    values:
      layout: "default"

title: "הכל בסדר"